=== Blitz517/android-debloat-list/schema/suggestion_list.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://muntashirakon.github.io/android-debloat-list/suggestion_list.json",
    "title": "Suggestion List",
    "description": "Listing of suggestions for Android bloatware",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "description": "Suggested package name",
                "type": "string"
            },
            "label": {
                "description": "Suggested package label",
                "type": "string"
            },
            "reason": {
                "description": "Reason for choosing this package if it violates some criteria",
                "type": "string"
            },
            "source": {
                "description": "Predefined list of app stores where this package might be located",
                "type": "string"
            },
            "repo": {
                "description": "Source code repository for this package",
                "type": "string"
            }
        },
        "required": [ "id", "label", "repo" ]
    },
    "uniqueItems": true
}

=== Blitz517/android-debloat-list/suggestions/browsers.json
[
    {
        "id": "org.bromite.bromite",
        "label": "Bromite",
        "source": "f",
        "repo": "https://github.com/bromite/bromite"
    },
    {
        "id": "org.chromium.chrome",
        "label": "Vanadium",
        "repo": "https://github.com/GrapheneOS/Vanadium",
        "reason": "GrapheneOS only"
    }
]

=== Blitz517/android-debloat-list/suggestions/barcode_scanners.json
[
    {
        "id": "de.markusfisch.android.binaryeye",
        "label": "Binary Eye",
        "source": "fg",
        "repo": "https://github.com/markusfisch/BinaryEye"
    },
    {
        "id": "com.atharok.barcodescanner",
        "label": "Barcode Scanner",
        "source": "f",
        "repo": "https://gitlab.com/Atharok/BarcodeScanner"
    }
]

=== Blitz517/android-debloat-list/suggestions/app_stores.json
[
    {
        "id": "com.aurora.store",
        "label": "Aurora Store",
        "reason": "Alternative Google Play Store client with privacy in mind.\nhttps://aurora-oss.vercel.app/faq/#aurora-store",
        "source": "f",
        "repo": "https://gitlab.com/AuroraOSS/AuroraStore"
    },
    {
        "id": "com.looker.droidify",
        "label": "Droid-ify",
        "source": "f",
        "repo": "https://github.com/Iamlooker/Droid-ify"
    }
]
